language: c
script: asdf plugin-test swift https://github.com/fcrespo82/asdf-swift.git 'asdf install swift 2.2'
before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
os:
  - linux
  - osx
sudo: required
language: generic
dist: trusty